module.exports = {
	extends: [
		'eslint:recommended',
	],
	rules: {
		indent: [ 'error', 'tab' ],
		'linebreak-style': [ 'error', 'unix' ],
		quotes: [ 'error', 'single' ],
		semi: [ 'error', 'always' ],
		'quote-props': [ 'error', 'as-needed' ],
		'array-bracket-spacing': [ 'error', 'always' ],
		'object-curly-spacing': [ 'error', 'always' ],
		'key-spacing': [ 'error', { beforeColon: false } ],
		'comma-spacing': [ 'error', { before: false, after: true } ],
		'no-multi-spaces': [ 'error' ],
		'no-multiple-empty-lines': [ 'error' ],
		'no-constructor-return': [ 'error' ],
		'no-duplicate-imports': [ 'error' ],
		'no-promise-executor-return': [ 'error' ],
		'no-self-compare': [ 'error' ],
		'no-use-before-define': [ 'error' ],
		'no-var': [ 'error' ],
		'prefer-const': [ 'error' ],
		'default-case-last': [ 'error' ],
		'default-param-last': [ 'error' ],
		'max-nested-callbacks': [ 'error', { max: 3 } ],
		'no-caller': [ 'error' ],
		'no-continue': [ 'error' ],
		'no-else-return': [ 'error' ],
		'no-eq-null': [ 'error' ],
		'no-eval': [ 'error' ],
		'no-implied-eval': [ 'error' ],
		'no-floating-decimal': [ 'error' ],
		'no-labels': [ 'error' ],
		'no-lonely-if': [ 'error' ],
		'no-negated-condition': [ 'error' ],
		'no-nested-ternary': [ 'error' ],
		'no-new-func': [ 'error' ],
		'no-param-reassign': [ 'error' ],
		'no-return-assign': [ 'error' ],
		'no-shadow': [ 'error' ],
		'no-undef-init': [ 'error' ],
		'no-unneeded-ternary': [ 'error' ],
		'no-useless-concat': [ 'error' ],
		'no-useless-return': [ 'error' ],
		'no-void': [ 'error' ],
		'prefer-destructuring': [ 'error' ],
		'prefer-exponentiation-operator': [ 'error' ],
		'prefer-template': [ 'error' ],
		radix: [ 'error' ],
		'require-await': [ 'error' ],
		yoda: [ 'error', 'never' ],
		eqeqeq: [ 'error', 'always' ],
		'spaced-comment': [ 'error',
			'always',
			{
				exceptions: [ '-',
					'+',
					'#',
					'=' ]
			} ],
		'no-trailing-spaces': [ 'error' ],
		'object-curly-newline': [ 'error', {
			ObjectExpression: { multiline: true, minProperties: 3 },
			ObjectPattern: { multiline: true, minProperties: 3 },
			ImportDeclaration: { multiline: true, minProperties: 3 },
			ExportDeclaration: { multiline: true, minProperties: 3 },
		} ],
		'array-element-newline': [ 'error', {
			ArrayExpression: { minItems: 3 },
			ArrayPattern: { minItems: 3 },
		} ],
		'object-property-newline': [ 'error', { allowAllPropertiesOnSameLine: true } ],
		'rest-spread-spacing': [ 'error' ],
		'space-before-function-paren': [ 'error', 'never' ],
		'space-in-parens': [ 'error', 'never' ],
		'space-infix-ops': [ 'error', { int32Hint: true } ],
		'template-curly-spacing': [ 'error', 'never' ]
	}
};