module.exports = {
	extends: [
		'eslint:recommended',
		'airbnb-base',
	],
	plugins: [

	],
	rules: {
		indent: [ 'error', 'tab' ],
		'linebreak-style': [ 'error', 'unix' ],
		quotes: [ 'error', 'single' ],
		semi: [ 'error', 'always' ],
		'quote-props': [ 'error', 'as-needed' ],
		'array-bracket-spacing': [ 'error', 'always' ],
		'object-curly-spacing': [ 'error', 'always' ],
		'key-spacing': [ 'error', { beforeColon: false } ],
		'no-constructor-return': [ 'error' ],
		'no-duplicate-imports': [ 'error' ],
		'no-self-compare': [ 'error' ],
		'no-use-before-define': [ 'error' ],
		'no-var': [ 'error' ],
		'prefer-const': [ 'error' ],
		'default-case-last': [ 'error' ],
		'default-param-last': [ 'error' ],
		'max-nested-callbacks': [ 'error', { max: 3 } ],
		'no-caller': [ 'error' ],
		'no-continue': [ 'error' ],
		'no-else-return': [ 'error' ],
		'no-eq-null': [ 'error' ],
		'no-eval': [ 'error' ],
		'no-implied-eval': [ 'error' ],
		'no-floating-decimal': [ 'error' ],
		'no-labels': [ 'error' ],
		'no-lonely-if': [ 'error' ],
		'no-negated-condition': [ 'error' ],
		'no-nested-ternary': [ 'error' ],
		'no-new-func': [ 'error' ],
		'no-param-reassign': [ 'error' ],
		'no-return-assign': [ 'error' ],
		'no-shadow': [ 'error' ],
		'no-undef-init': [ 'error' ],
		'no-unneeded-ternary': [ 'error' ],
		'no-useless-concat': [ 'error' ],
		'no-useless-return': [ 'error' ],
		'no-void': [ 'error' ],
		'prefer-exponentiation-operator': [ 'error' ],
		'prefer-template': [ 'error' ],
		radix: [ 'error' ],
		'require-await': [ 'error' ],
		yoda: [ 'error', 'never' ],
		eqeqeq: [ 'error', 'always' ],
		'max-len': [
			'error',
			120,
			2,
			{
				ignoreUrls: true,
				ignoreComments: false,
				ignoreRegExpLiterals: true,
				ignoreStrings: true,
				ignoreTemplateLiterals: true,
			},
		],
		'prefer-destructuring': [
			'error',
			{
				VariableDeclarator: {
					array: false,
					object: true,
				},
				AssignmentExpression: {
					array: false,
					object: false,
				},
			},
			{ enforceForRenamedProperties: false },
		],
		'no-tabs': 'off',
		'import/extensions': [ 'error', 'never' ],
		'import/no-cycle': 'off',
		'import/prefer-default-export': 'off',

	},
};
