
name: CI

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 17
      uses: actions/setup-node@v2
      with:
        node-version: 17
        cache: 'yarn'
    - run: yarn
    - run: yarn lint
